### ISSUE TITLE
Split index quantification 

### ISSUE THREAD

**Issue by BioFalcon** [pachterlab/kb_python#138]
Hello,

I was running the custom index for RNA velocity pipeline as described in the kallistobus.tools site and noticed that `kb ref` generates multiple files (`MM38_intron.X and MM38_cDNA`) but doesn't generate the index file as specified (MM38). So when trying to run it on `kb count` it says that it cannot find the index. Is there a way to specify it/ merge it?

Also on another note, would it be possible to parallelize the index construction for the velocity when the intron files are split?

Thank you! :)

**Comment by Lioscro** [comment]
Hi, @BioFalcon,
Are you using the `-n` option when running `kb ref`?
This option specifies the number of indicies to split the reference into, and all of these must be specified as a comma-delimited list as the input to the `-i` option when running `kb count`. For instance, if `index_cDNA.idx` and `index_intron.0.idx` are your split indices, you should specify `-i index_cDNA.idx,index_intron.0.idx`.

Also, split indices are solely for the purpose of reducing memory requirements when building the index and aligning the reads. Parallelizing this process would defeat that purpose. If you have enough memory to build the full index, it is always recommended that you do so (instead of splitting, because splitting comes with some caveats).
