### ISSUE TITLE
clarification on kb ref function

### ISSUE THREAD

**Issue by mninova** [pachterlab/kb_python#150]
Hi, thank you for the great tool, I love how efficient it is. Not a real issue but more of a clarification:

I want to make a custom beyond standard annotations. When analyzing bulk RNA-seq, to do that I'd just concatenate transcriptome + whatever custom transcripts I want to analyze to build a kallisto index. However, I see that kb ref takes genome fasta + gtf file (as opposed to transcript fasta): could you clarify how kb refs processes these inputs and what's the best way to add custom transcripts?

**Comment by sbooeshaghi** [comment]
Thank you for the question! 

kb ref takes the genome fasta and the gtf file so that it can build the transcriptome from the gtf. This allows us to grab the transcript IDs and gene IDs from the gtf file (along with other metadata) allowing us to make a transcripts-to-genes file (t2g.txt). That file is necessary when running kb count as it allows us to create a gene count matrix from transcript counts. The kallisto index that is generated from kb ref can be thought of being generated in the following way: extract all of the transcripts from the genome into a fasta file (using the gtf as a guide) and run kallisto index on that file.

To add custom transcripts what one could do is create entries in the genome and gtf that correspond to "transcripts" with each entry in the genome fasta / gtf pair corresponding to a custom "transcript" sequence.

Alternatively one could take the transcripts.fasta file that is generated by kb ref (with the -f1 flag) and do the standard method of concatenating custom transcript sequences to that file (and making sure that the t2g.txt file also has a mapping of the custom transcript name to the custom transcript name (or other mapping to collate multiple custom transcripts) so that the count command knows how to count those sequences appropriately.)

I hope that helps!

**Comment by mninova** [comment]
Yes, I added custom annotation to the gtf and everything worked fine, thank you!
