### ISSUE TITLE
Usage of f1 and f2 parameters in kb ref and count

### ISSUE THREAD

**Issue by NikTuzov** [pachterlab/kb_python#248]
Hello Delaney:

I am trying to run the "nac" workflow. 
Based on the help info I got directly from the command line for kb ref, both f1 and f2 parameters are compulsory.  However, kb count help doesn't mention f1 and f2 at all. I looked at Sullivan et al paper and there the situation is similar: f1 and f2 are used only with kb ref. Why make them compulsory if the corresponding outputs are not used downstream in kb count?

Version info:
kb_python 0.28.0
kallisto (version 0.50.1)
bustools (version 0.43.1):

Regards,
Nik Tuzov

**Comment by Yenaled** [comment]
This has always been the case with kb-python since its development over 3 years ago (before I joined the Pachter group). I have decided not to change this behavior. The output files aren’t that big (and you can delete them after). But, more importantly, those FASTA files store the precise plaintext nucleotide sequences that we map reads against (and it is desirable to associate such files with the index — if those files don’t exist, well, then it’s impossible to recover what you actually put in your index).

**Comment by NikTuzov** [comment]
Thank you!
