### ISSUE TITLE
kb-python for MARS-seq

### ISSUE THREAD

**Issue by sam-shariati** [pachterlab/kb_python#252]
Hi, I have been using kb-python to analyze scRNA-seq. first, thanks for creating such a user-friendly and useful tool. I appreciate it! I just had a technical issue when reanalyzing scRNA-seq in [this paper](https://www.cell.com/cell-stem-cell/pdf/S1934-5909(22)00377-0.pdf) by Lau et al in which they have used [MARS-seq](https://www.nature.com/articles/s41596-019-0164-4). My question is that when I wanted to run kb count , I couldn't figure out what would the best code to use to specify umi/barcos of the mars-seq (-x). I couldn't find mars-seq when I ran kb --list and i tried a few codes but was not successful. I was hoping that you may have encountered this issue before or may have already a solution for it. Thanks!
ps I accidentally posted this very same comment for kallisto too.

**Comment by Yenaled** [comment]
I'll be honest: I've never actually analyzed MARS-seq data.

From what I can find online, it seems like R2 contains a 7-bp barcode + 8-bp UMI, while R1 has a 4-bp barcode after the first 3 nucleotides, then those 7 bp's are followed by the sequence to be mapped.

If this is the case, then the technology string will be:

`-x 0,3,7,1,0,7:1,7,15:0,7,0`

This means take the 4-bp barcode of R1 concatenated with the 7-bp barcode of R2, extract the 8-bp UMI from R2, and extract the sequence-to-be-mapped from R1.

What is important to have is the list of barcodes provided by the assay. I can't provide that for you since it's experiment-specific. The list of barcodes provided should be the 4-bp (pool) barcode followed by the 7-bp (cell) barcode
