### ISSUE TITLE
Installing kb-python without pip

### ISSUE THREAD

**Issue by mstemmer** [pachterlab/kb_python#65]
Thank you very much for this great tool!

It works nicely, but also would like to use it on a machine, where I cant use pip for several reasons. Is there any plan to include kb-python in anaconda? 
Or, what would be the best way to compile the package from source?

**Comment by Lioscro** [comment]
Hi, @mstemmer,

Currently, there are no plans to include `kb` in anaconda since `pip` comes with conda and that should suffice for most use cases.

If you are unable to use `pip`, the following commands should work.
```
$ conda install conda-build
$ conda skeleton pypi kb_python
$ conda build kb_python
$ conda install --use-local kb_python
```
I adapted the following commands from this stackoverflow post: https://stackoverflow.com/questions/29286624/how-to-install-pypi-packages-using-anaconda-conda-command.

Unfortunately, this does not allow compiling from source directly, only from versions released to PyPI.

**Comment by mstemmer** [comment]
Hi, @Lioscro ,
thanks! I got it to work.

**Comment by Maarten-vd-Sande** [comment]
Just a little FYI I just added kb_python to bioconda:

https://anaconda.org/bioconda/kb-python

` conda install -c bioconda kb-python  `

**Comment by marykthompson** [comment]
@Maarten-vd-Sande out of curiosity, can you explain how you were able to package it for conda? I had tried doing this in the past with conda skeleton but it failed due to kb-python not having a requirements.txt file in PyPi.

**Comment by Maarten-vd-Sande** [comment]
Not sure how conda skeleton works. In general when I add packages to (bio)conda I just copy a meta.yaml from another package and change it to fit with the new package. This is the final [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kb-python/meta.yaml) for kb-python.

If I recall correctly there was a bit of a problem with some dependencies not being updated anymore / packages not yet on conda. But those can be resolved in the same way. If you have problems with adding a package, you can always ask for help on the bioconda gitter or conda-forge gitter. Really helpful people on there!

**Comment by marykthompson** [comment]
Thanks! I have been fairly unsuccessful in making my own conda packages in the past but I would really like to learn as conda is my primary package manager. Btw, when I tried installing kb-python with conda install just now on my machine, I got a blank UnsatisfiableError. Not sure where to go from there.

**Comment by Maarten-vd-Sande** [comment]
Oh that is strange.. :thinking: 

`UnsatisfiableError` generally means that there are conflicting packages. Does installing in a fresh environment work?

**Comment by marykthompson** [comment]
I think it has to do with the loompy version available on anaconda.org.
When I try this,:
conda create -n kbtest2 -c bioconda kb-python loompy

I get: 
Package loompy conflicts for:
kb-python -> loompy[version='>=3.0.6']
loompy

**Comment by Maarten-vd-Sande** [comment]
Do you have conda-forge added as a channel?

**Comment by marykthompson** [comment]
Yes, thanks. I really thought I had conda-forge added, but it must have gotten removed at some point. The problem is that I installed loompy from bioconda, which is still using version 2. kb-python requires version 3, which can be installed from conda-forge. I don't know why it conda doesn't report that as the unsatisfiable error though (regardless of a channel being added or not).

**Comment by marykthompson** [comment]
@Maarten-vd-Sande If I may ask one further question for my own enlightenment, how did you figure out the run requirements of kb-python for making the meta.yaml file? I see that the anndata and loompy dependencies are listed in the package itself (in the requires.txt file), but the requests and tqdm dependencies are not. Do you first install the package with pip and then figure out the dependencies somehow from that installation?

**Comment by Maarten-vd-Sande** [comment]
I guess I took it from the requirements file:

https://github.com/pachterlab/kb_python/blob/master/requirements.txt
