### ISSUE TITLE
Error in generating RNA count matrices

### ISSUE THREAD

**Issue by hlee11** [pachterlab/kb_python#69]
Hello, I'm mostly following kb_single_nucleus.ipynb to analyze mouse 10x3 single nucleus sequencing data.  1) I append a Cre-recombinase sequence and a EGFP sequence to the Mus_musculus.GRCm38.dna.primary_assembly.fa 2) I append both CRE and EGFP to the Mus_musculus.GRCm38.100.gtf
Everything seemed to work fine until the last step of generating RNA count matrices.  In the output/counts_unfiltered, I see 6 files are generated (spliced.mtx, spliced.genes.txt, spliced.barcodes.txt, unspliced.mtx, unspliced.genes.txt, unspliced.barcodes.txt) after ~3 hours. And suddenly it stopped with a ValueError: could not convert integer scalar
I THINK it somehow can't do few last steps to write matrices for making .h5ad
Would you please take a look the Traceback and help me?

![image](https://user-images.githubusercontent.com/64625943/80781000-dbcb7a00-8b3e-11ea-956f-50c1414f80d0.png)

**Comment by Lioscro** [comment]
Scipy has some issues dealing with large sparse matrices. Since it seems like you have the matrix file, could you check how many rows are in the matrix?

**Comment by hlee11** [comment]
After I created this issue, by Googling, I was able to manually combine the matrix (both unspliced and spliced) for each samples and further combine the two samples (sample 1 and 2 under the 'batch' obs) into one aggregated AnnData object. **So thank you very much for previous answers under:**
https://github.com/pachterlab/kb_python/issues/61
and
https://github.com/BUStools/getting_started/blob/master/kallisto_bus_mouse_nuclei_tutorial.ipynb

According to this issue:
https://github.com/pachterlab/kb_python/issues/52
 your team is planning to release next version of the kb with a function that finds ENSMUSGxxxx and returns gene_name (gene symbol).  **May I ask when?** (I mean, is it going to happen within a month, 6 months, or was it meant 'just some time in future...')

I can obviously open the t2g.txt in excel and manually search for the corresponding gene ID, but what I'd like to do is:
Currently I'm following scanpy tutorial and was able to get all the plots with ENSMUSGxxxx so I would highly appreciate if there is a 'temporary' tip to just swap ENSMUSGxxxx to gene_name.  **Could you provide a few lines of code here as an example so that I can start applying to the code that I'm running?**  I've used R and only recently started self-educating python, in order to try kallistobus, thus I'm not super familiar with AnnData format and python-style coding. Thus any advice would be helpful.

**Comment by Lioscro** [comment]
Hi, @hlee11,

Glad that you got the issue resolved.
We are planning to release it once a new version of Bustools is released, since a `kb` feature depends on a new bustools feature that is still currently in the development branch. We expect this to happen within the next couple of months.

If you are okay with using the development version, you can manually pip install the `kb` development version, which contains the change you are looking for. Just run the following command.
```
pip install git+https://github.com/pachterlab/kb_python@devel --upgrade
```

You can think of an Anndata object as a matrix with pandas dataframes as rows and columns, so that we can add additional annotations to rows and columns. For instance, the anndata file that is generated when running kb with the `--h5ad` option can be loaded with.
````python
import anndata
adata = anndata.read_h5ad(PATH_TO_H5AD)
````
and you can access the row and columns with 
````python
adata.obs  # rows are called obs (short for observation)
adata.var   # columns are called var (short for variable)
````
which are each pandas dataframes.
To add gene names to the columns (i.e. var), you would first load a transcript-to-gene dictionary (you can generate this by simply reading the t2g row by row) and looking up the gene for each transcript.
```python
adata.var['gene_name'] = adata.var['gene_id'].apply(lambda x: t2g[x])
```
Assuming the transcript-to-gene dictionary is `t2g`.

**Comment by hlee11** [comment]
Hi @Lioscro ,
Thank you for the suggestion.  I've re-installed everything yesterday, so I'm using the development version that is most recent.  Also I've down-greaded the gcc compiler i.e., I was using GCC 10.1 on Catalina (macOS 10.15) but now I'm using the gfortran 8.2 for Mojave (macOS 10.14) on Catalina.

Interestingly, I don't need to manually combine matrices in this setting- kb_python works without error and generates one adata.h5ad   :-)

But the issue with displaying official gene symbols instead of ENSMUSGxxxx seems to still be there, in this development version.  With scanpy all graphs are created nicely with Ensemble IDs.  Is there additional step that I need to do, in order to switch from gene_id to gene_name?

FYI, I also tried your code but got error:
![image](https://user-images.githubusercontent.com/64625943/84612660-476b6b80-ae8f-11ea-8a2c-83d20f7d4a5c.png)

**Comment by Lioscro** [comment]
Ah, I see where the issue may be.
The following should work.
```
adata.var['gene_name'] = adata.var.index.map(lambda x: t2g[x])
```
Or, you could rerun after installing the devel version of kb.
