### ISSUE TITLE
Support for CELSeq2 384 barcode format

### ISSUE THREAD

**Issue by paristau** [pachterlab/kb_python#70]
Hi,

Thank you for developing these tools. I find it very useful.
We have CELSeq2 scRNA datasets with 384 barcode combination. It is slightly different from the usual CELSeq2 configuration

The R1 contains 7bp UMI +7 bp barcode instead of the usual 6 +6 combination. Is it possible to add support for this kind of dataset as well?

Thanks in advance.

**Comment by Lioscro** [comment]
Hi, @paristau 
Thanks for reaching out.
We can look into adding that to either `kb` or `kallisto`.
In the meantime, you can manually specify the barcode and UMI positions instead of using one of the predefined technologies to the `-x` argument.
More information is in the `bus` section of the `kallisto` manual here: https://pachterlab.github.io/kallisto/manual

For your case, you can provide `-x 0,7,14:0,0,7:1,0,0` instead of the usual `-x celseq2`.

**Comment by paristau** [comment]
Thanks @Lioscro.

Manually specifying the barcode and UMI configuration worked.
