### ISSUE TITLE
Question about choice of flank parameter for intron fasta

### ISSUE THREAD

**Issue by marykthompson** [pachterlab/kb_python#86]
I am curious about how the flank parameter (number of flanking exon nucleotides) on each side of the intron is chosen for the intron fasta file. In kb_python/fasta.py generate_intron_fasta(), 30 nt is used (related to kmer = 31 -1).

Whereas with this other source I found they use the sequencing read length -1: https://rdrr.io/github/lambdamoses/BUStoolsR/man/get_velocity_files.html (e.g. for 80 bp reads, flank = 79).

The second approach is obviously more inconvenient because you would have to rebuild the index for libraries of different read lengths instead of using the same index for different libraries. Because the max kmer length (-k) in Kallisto index is 31, does this mean that there is no benefit to pseudoalignment if you set flank > 30? It does seem like in theory you would have reads that overlap the intron only at the end of a long read, but would Kallisto detect them better
if you set the flank parameter to be longer?

**Comment by Lioscro** [comment]
Hi, @marykthompson,
You are absolutely correct: because the kmer length in the kallisto index is 31, there is no benefit of having the flank be greater than 30, since the reads will be split into 31-mers during pseudoalignment.

Even if you have a long read that overlaps the intron only at the end, kallisto aligns each kmer (in this case, 31-mer) to the index, so it is still be able to detect an intronic read that way.

**Comment by marykthompson** [comment]
Thanks for explaining. I thought this was probably the case but I was confused by the BUStoolsR reference above.
